# Phase: Foundations — ML Task Framing & Problem Definition
**Student:** Muhammad Zohaib Shahid  
**Domain/Lane:** E-Commerce Store & Content Audit (Shopify / Web Development)  
**Repository Target Path:** `work/notebooks/w02_ml_task_framing.ipynb`

## 1. My Lane as an ML Task (Type)

- **Task Type:** Binary Classification & Scoring
- **Definition:** Predict whether a given Shopify store landing page or product page is at high risk of low checkout conversion due to page performance, layout friction, or SEO content gaps.
- **Goal:** Automatically flag underperforming store pages for technical audits and optimization.

## 2. Target or Proxy

- **Target Variable (`is_high_risk_conversion`):**
  - `1` = High Risk / Low Converting Page (e.g., Page Load Speed > 3.5s, High Bounce Rate, Missing Meta/Product Description, Low Mobile Usability Score).
  - `0` = Optimized / High Converting Page.
- **Proxy Rationale:** Real-time conversion rate data is often restricted or delayed. Therefore, technical performance metrics (LCP, CLS, DOM depth, word count, schema tags) act as a strong proxy for user friction and conversion failure.

## 3. Success Metric

- **Primary Metric:** **Precision @ Top K (and Recall for High-Risk Pages)**
- **Business Rationale:** False Positives waste engineering time auditing store pages that are already fine. We need high Precision so that when the system flags a page as "High Risk," it almost certainly needs technical refactoring.
- **Secondary Metric:** F1-Score to maintain balance between catching broken pages and avoiding false alarms.

## 4. The Unit of Analysis (Real Dataframe)

- **Unit of Analysis:** **ONE ROW = ONE SHOPIFY STORE URL / PAGE**

In [1]:
import pandas as pd
import numpy as np

# Starter data slice for FlyRank / Store Audit Lane
data = {
    'page_id': ['PAGE_101', 'PAGE_102', 'PAGE_103', 'PAGE_104', 'PAGE_105'],
    'page_type': ['product', 'landing', 'collection', 'product', 'landing'],
    'load_time_seconds': [4.2, 1.8, 2.5, 5.1, 1.2],
    'mobile_usability_score': [45, 92, 78, 38, 95],
    'word_count': [120, 850, 310, 80, 1100],
    'has_schema_markup': [0, 1, 1, 0, 1],
    'bounce_rate_pct': [68.5, 24.1, 41.2, 79.0, 18.5]
}

df = pd.DataFrame(data)

print("--- Section 4: Unit of Analysis (Real Dataframe) ---")
print("Unit of Analysis: One row represents one unique Shopify Store URL / Page.")
df

--- Section 4: Unit of Analysis (Real Dataframe) ---
Unit of Analysis: One row represents one unique Shopify Store URL / Page.

    page_id   page_type  load_time_seconds  mobile_usability_score  word_count  has_schema_markup  bounce_rate_pct
0  PAGE_101     product                4.2                      45         120                  0             68.5
1  PAGE_102     landing                1.8                      92         850                  1             24.1
2  PAGE_103  collection                2.5                      78         310                  1             41.2
3  PAGE_104     product                5.1                      38          80                  0             79.0
4  PAGE_105     landing                1.2                      95        1100                  1             18.5

In [2]:
# Target Proxy Sketching
# High Risk (1) if Load Time > 3.5s OR Mobile Score < 50
df['target_high_risk'] = np.where((df['load_time_seconds'] > 3.5) | (df['mobile_usability_score'] < 50), 1, 0)

print("--- Dataframe with Target Proxy Column (`target_high_risk`) ---")
df[['page_id', 'page_type', 'load_time_seconds', 'mobile_usability_score', 'target_high_risk']]

--- Dataframe with Target Proxy Column (`target_high_risk`) ---

    page_id   page_type  load_time_seconds  mobile_usability_score  target_high_risk
0  PAGE_101     product                4.2                      45                 1
1  PAGE_102     landing                1.8                      92                 0
2  PAGE_103  collection                2.5                      78                 0
3  PAGE_104     product                5.1                      38                 1
4  PAGE_105     landing                1.2                      95                 0

## 5. Why ML Beats a Fixed Rule Here

1. **Non-Linear Interacting Factors:** A static rule like `if load_time > 3s THEN alert` fails because a page with a 3.2s load time might still convert extremely well if it has exceptional social proof, clear schema, and high mobile usability. ML captures complex non-linear feature interactions.
2. **Adaptability Across Niches:** Different e-commerce niches (e.g., fashion vs. high-ticket electronics) have different user tolerances for page layout and speed. ML models adapt to distribution shifts faster than hardcoded `if-else` scripts.
3. **Action Triggered:** The ML prediction directly triggers an automated **Audit & Refactoring Brief** sent to the client or developer, prioritizing pages with the highest predicted risk score.

## 6. Self-Check

- [x] **Task Type Named:** Binary Classification / Risk Scoring
- [x] **Target/Proxy Defined:** `target_high_risk` based on technical store performance
- [x] **Success Metric Specified:** Precision @ K & F1-Score
- [x] **Unit of Analysis Clear:** One row = One Shopify Store Page / URL
- [x] **ML vs Rule Rationale:** Non-linear feature interaction & adaptability explained
- [x] **Action Connection:** Output directly feeds technical store audit briefs